BINANCE_API_KEY: your_binance_api_key
BINANCE_API_SECRET: your_binance_api_secret
DEMO_MODE: true
EXCHANGE: exness
EXNESS_LOGIN: your_exness_login
EXNESS_PASSWORD: your_exness_password
EXNESS_SERVER: Exness-MT5
FMP_API_KEY: 8Z3mPEMSUcT9GiZmmgGcnDBIZloylElz
FOREX_LOT_SIZE: 0.01
FOREX_SPREAD_LIMIT: 50
FOREX_SYMBOLS:
- EURUSD
- GBPUSD
- USDJPY
- USDCHF
- AUDUSD
- USDCAD
- NZDUSD
MAX_CONSECUTIVE_LOSSES: 5
MIN_CONFIDENCE: 70
MIN_WIN_RATE: 0.3
OANDA_ACCOUNT_ID: your_oanda_account_id
OANDA_API_KEY: your_oanda_api_key
TELEGRAM_BOT_TOKEN: your_telegram_bot_token
TELEGRAM_CHAT_ID: your_telegram_chat_id
TRADING_HOURS:
  end: '23:59'
  start: 00:00
commission_rate: 5.0e-05
data_provider: YAHOO
enable_dashboard: true
enable_notifications: true
execution_engine: EXTREME
extreme_mode: true
initial_balance: 1000000.0
leverage: 2000
log_level: INFO
martingale_enabled: true
max_drawdown_threshold: 0.8
max_positions: 20
news_trading_enabled: true
position_sizing_method: FIXED_PERCENTAGE
risk_per_trade: 0.6
scalping_enabled: true
slippage_rate: 0.0003
stop_loss_method: ATR
strategies:
- confidence_threshold: 0.95
  max_holding_minutes: 1
  name: Scalper_1
  timeframe: 1m
  type: EXTREME_SCALPING
- name: News_Trader_1
  news_impact_threshold: HIGH
  reaction_time_seconds: 3
  type: NEWS_EXPLOSION
- momentum_threshold: 0.03
  name: Momentum_1
  type: BREAKOUT_MOMENTUM
  volume_confirmation: true
- max_levels: 8
  name: Recovery_1
  recovery_target: 0.1
  type: MARTINGALE_EXTREME
strategy_weights:
  Momentum_1: 0.2
  News_Trader_1: 0.3
  Recovery_1: 0.1
  Scalper_1: 0.4
take_profit_ratio: 2.0
