initial_balance: 1000000
leverage: 2000
max_daily_loss: 0.8
max_drawdown: 0.9
max_positions: 10
max_risk_per_trade: 0.5
name: Ultra_Extreme_7D
strategies:
- name: Ultra_Scalping_1
  risk_per_trade: 0.5
  type: ULTRA_SCALPING
  weight: 0.3
- name: Volatility_Explosion_1
  risk_per_trade: 0.5
  type: VOLATILITY_EXPLOSION
  weight: 0.3
- name: News_Impact_1
  risk_per_trade: 0.5
  type: NEWS_IMPACT
  weight: 0.4
symbols:
- EURUSD
- GBPUSD
- USDJPY
- XAUUSD
