exness:
  base_currency: IDR
  leverage: 2000
  login: 0
  password: ''
  server: Exness-MT5Real
monitoring:
  heartbeat_interval: 60
  report_interval: 300
  update_interval: 30
risk_management:
  emergency_stop_loss: 0.7
  max_daily_loss: 0.3
  max_drawdown: 0.5
  max_positions: 5
  max_risk_per_trade: 0.2
trading:
  initial_balance: 1000000
  strategies:
  - name: Ultra_Scalping_1
    type: ULTRA_SCALPING
    weight: 0.25
  - name: Volatility_Explosion_1
    type: VOLATILITY_EXPLOSION
    weight: 0.25
  - name: Momentum_Surge_1
    type: MOMENTUM_SURGE
    weight: 0.25
  - name: News_Impact_1
    type: NEWS_IMPACT
    weight: 0.25
  symbols:
  - EURUSD
  - GBPUSD
  - USDJPY
  - XAUUSD
  target_balance: 2000000000
  target_days: 15
